select
  event.event_id,
  event.occurred_at,
  event.state,
  event.county,
  event.begin_location,
  event.end_location,
  event.rating_code,
  cast(null as varchar) as scale_system,
  cast(null as integer) as rating_value,
  cast('Preliminary report' as varchar) as intensity_class,
  cast(null as integer) as wind_estimate_low_mph,
  cast(null as integer) as wind_estimate_high_mph,
  cast('Preliminary Local Storm Reports do not include a damage-based F or EF wind estimate.' as varchar) as wind_estimate_note,
  event.path_length_miles,
  event.path_width_yards,
  event.begin_latitude,
  event.begin_longitude,
  event.end_latitude,
  event.end_longitude,
  event.injuries,
  event.fatalities,
  event.property_damage_usd,
  event.crop_damage_usd,
  event.event_narrative as narrative,
  event.source_url,
  event.report_source,
  event.wfo,
  event.state = 'AL' as is_alabama,
  event.state in ('AL', 'AR', 'GA', 'LA', 'MS', 'TN') as is_dixie_cohort,
  event.state in ('CO', 'IA', 'KS', 'NE', 'OK', 'SD', 'TX') as is_tornado_cohort
from {{ ref('src_iem__preliminary_tornado_reports') }} as event
